site_name: django-iubenda
site_url: https://github.com/DLRSP/django-iubenda/
site_description: Django application for Iubenda privacy and cookie policies.

repo_name: DLRSP/django-iubenda
repo_url: https://github.com/DLRSP/django-iubenda/

theme:
    name: 'material'
    palette:
      - scheme: default
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - scheme: slate #
        toggle:
          icon: material/weather-night
          name: Switch to light mode
    features:
      - navigation.instant
      - navigation.top
      - content.code.annotate
      - content.tabs.link
      - search.suggest
      - search.highlight
    icon:
        repo: fontawesome/brands/github-alt

plugins:
  - search
  - git-revision-date
#  - tags

extra:
  analytics:
    provider: google
    property: G-WL6PWX05L4
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DlrspTwits
      name: DLRSP on Twitter
    - icon: fontawesome/solid/paper-plane
      link: mailto:dlrsp.dev@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/DLRSP

markdown_extensions:
 - toc:
    anchorlink: True
 - pymdownx.tabbed:
    alternate_style: true
 - pymdownx.highlight:
 - pymdownx.inlinehilite:
 - pymdownx.superfences:
 - pymdownx.snippets:

nav:
 - Home: 'index.md'
 - Tutorials:
    - 'Example project': 'tutorial/example.md'
    - 'Customize overview': 'tutorial/customize.md'
    - 'Configuration (APP_CONFIG)': 'tutorial/configuration.md'
    - 'Templates': 'tutorial/templates.md'
    - 'HTTP client & policy API': 'tutorial/http-api.md'
    - 'Google Tag Manager': 'tutorial/google-gtm.md'
 - Community:
    - 'Contributing': 'community/contributing.md'
    - 'References': 'community/references.md'

copyright: Copyright &copy; 2010-present DLRSP
